# Site settings
title: Tilde New Music and Sound Art
email: info@tilde.net.au
description: "Tilde New Music and Sound Art launched at the beginning of 2014, offering a platform and communal space for new and experimental music practice."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://staging.tilde.net.au" # the base hostname & protocol for your site

squareLogo: assets/img/tilde-logo.jpg

# Podcast settings
podcastTitle: Tilde
podcastAuthor: Tilde New Music
podcastDescription: Description of the podcast
podcastOwner: Tilde New Music
podcastEmail: info@tilde.net.au
podcastCategory: Music

# Build settings
markdown: kramdown
sass:
  style: compressed

exclude:
  - bower_components
  - node_modules
  - assets/js/src
  - assets/bower_components
  - gulpfile.js
  - package.json
  - bower.json
  - Gemfile
  - Gemfile.lock
  - bower.json
  - rakefile
  - .*

collections:
  podcast:
    output: false

prose:
  ignore:
    - _includes
    - _layouts
    - _plugins
    - _sass
    - assets
    - .bowerrc
    - .gitignore
    - Gemfile*
    - _config*
    - bower.json
    - feed.xml
    - gulpfile.js
    - package.json
    - rakefile
    - links.jsonp
    - podcast.xml
    - robots.txt
  media: "images/"
  siteurl: "http://tilde.net.au.s3-website-ap-southeast-2.amazonaws.com"
  relativelinks: "http://tilde.net.au.s3-website-ap-southeast-2.amazonaws.com/links.jsonp"
  metadata:
    pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
          label: "Layout"
      - name: "title"
        field:
          element: "text"
          value: ""
          label: "Title"
          placeholder: "Page Title"
      - name: "permalink"
        field:
          element: "text"
          value: ""
          placeholder: "/directory/"
          label: "Permalink"
    _podcast:
      - name: "date"
        field:
          element: "text"
          value: CURRENT_DATETIME
          label: "Post date"
      - name: "title"
        field:
          element: "text"
          label: "Episode Title"
      - name: "subtitle"
        field:
          element: "text"
          label: "Episode Subtitle"
      - name: "keywords"
        field:
          element: "text"
          placeholder: ""
          label: "Keywords"
      - name: "image"
        field:
          element: "text"
          value: ""
          label: "Image URL"
          placeholder: "http://podcast.tilde.net.au/<guid>/<podcast artwork file>"
      - name: "guid"
        field:
          element: "text"
          placeholder: "000"
          label: "Three digit Episode number"
      - name: "pubDate"
        field:
          element: "text"
          value: CURRENT_DATETIME
          label: "pubDate"
      - name: "enclosureUrl"
        field:
          element: "text"
          value: ""
          label: Audio file URL
          placeholder: "http://podcast.tilde.net.au/<guid>/<podcast audio file>"
      - name: "enclosureLength"
        field:
          element: "number"
          value: "0"
          label: "File length in bytes"
      - name: "enclosureType"
        field:
          element: "select"
          options:
            - name: "MP3"
              value: "audio/mpeg"
            - name: "M4A"
              value: "audio/x-m4a"
            - name: "MP4"
              value: "video/mp4"
            - name: "M4V"
              value: "video/x-m4v"
            - name: "MOV"
              value: "video/quicktime"
          label: Enclosure Type
      - name: "duration"
        field:
          element: "text"
          placeholder: "4:33"
          label: "Duration"
