# Site settings
title: Tilde New Music and Sound Art
email: kevan@kevanatkins.com
description: "Tilde New Music and Sound Art launched at the beginning of 2014, offering a platform and communal space for new and experimental music practice."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tilde.net.au" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['bower_components', 'node_modules', 'assets/js/src', 'assets/bower_components', 'gulpfile.js', 'package.json', 'bower.json', 'Gemfile', 'Gemfile.lock', 'bower.json', 'rakefile', '.*']

prose:
  ignore: ['_includes', '_layouts', '_plugins', '_sass', '.bowerrc', '.gitignore', 'Gemfile*', '_config*', 'bower.json', 'feed.xml', 'gulpfile.js', 'package.json', 'rakefile']
