# Site settings
title: Tilde New Music and Sound Art
email: info@tilde.net.au
description: "Tilde New Music and Sound Art launched at the beginning of 2014, offering a platform and communal space for new and experimental music practice."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tilde-festival-website.s3-website-ap-southeast-2.amazonaws.com" # the base hostname & protocol for your site

squareLogo: assets/img/tilde-logo.jpg

# Podcast settings
podcastTitle: Tilde
podcastAuthor: Tilde New Music
podcastDescription: Description of the podcast
podcastOwner: Tilde New Music
podcastEmail: info@tilde.net.au
podcastCategory: Music

# Build settings
markdown: kramdown
sass:
  style: compressed

exclude: ['bower_components', 'node_modules', 'assets/js/src', 'assets/bower_components', 'gulpfile.js', 'package.json', 'bower.json', 'Gemfile', 'Gemfile.lock', 'bower.json', 'rakefile', '.*']

collections:
  podcast:
    output: false

prose:
  ignore:
    - _includes
    - _layouts
    - _plugins
    - _sass
    - assets
    - .bowerrc
    - .gitignore
    - Gemfile*
    - _config*
    - bower.json
    - feed.xml
    - gulpfile.js
    - package.json
    - rakefile
    - links.jsonp
    - podcast.xml
  media: "images/"
  siteurl: "http://tilde-festival-website.s3-website-ap-southeast-2.amazonaws.com"
  relativelinks: "http://tilde-festival-website.s3-website-ap-southeast-2.amazonaws.com/links.jsonp"
  metadata:
    _podcast:
      - name: "date"
        field:
          element: "text"
          value: CURRENT_DATETIME
      - name: "title"
        field:
          element: "text"
          value: ""
          placeholder: "Episode Title"
      - name: "subtitle"
        field:
          element: "text"
          value: ""
          placeholder: "Episode Subtitle"
      - name: "keywords"
        field:
          element: "text"
          value: ""
          placeholder: "Keywords"
      - name: "image"
        field:
          element: "text"
          value: ""
          placeholder: "Image URL here"
      - name: "guid"
        field:
          element: "number"
          value: ""
          placeholder: "Three digit Episode number"
      - name: "pubDate"
        field:
          element: "text"
          value: CURRENT_DATETIME
          label: "pubDate"
      - name: "enclosureUrl"
        field:
          element: "text"
          value: ""
          placeholder: "http://podcast.tilde.net.au/<podcast episode URL>"
      - name: "enclosureLength"
        field:
          element: "number"
          value: ""
          placeholder: "File length in bytes"
      - name: "enclosureType"
        field:
          element: "text"
          value: "audio/mpeg"
          placeholder: Enclosure Type
      - name: "duration"
        field:
          element: "text"
          value: "4:33"
          placeholder: "Duration"
